### ISSUE TITLE
配置错误

### ISSUE THREAD

**Issue by Unicorni** [KudouRan/BiliTools#107]
### 运行环境和版本

腾讯云函数   青龙脚本2.12.1

### 发生了什么

这里有一个bug! 我希望它能这样。

### 相关的日志输出

```shell
我的青龙脚本2.12.1  到教程和视频内 task bilitools_npm.js 这部出错 ，内面是require('@catlair/bilitools').ql();

[error 23:24:54] Error: Expected ':' instead of ','
/usr/local/pnpm-global/5/node_modules/.pnpm/@catlair+bilitools@0.5.220801/node_modules/@catlair/bilitools/dist/utils/file.js:53
  throw new Error(message);
        ^

Error: Expected ':' instead of ','
    at jsonErrorHandle (/usr/local/pnpm-global/5/node_modules/.pnpm/@catlair+bilitools@0.5.220801/node_modules/@catlair/bilitools/dist/utils/file.js:53:9)
    at readJsonFile (/usr/local/pnpm-global/5/node_modules/.pnpm/@catlair+bilitools@0.5.220801/node_modules/@catlair/bilitools/dist/utils/file.js:40:5)
    at setConfig (/usr/local/pnpm-global/5/node_modules/.pnpm/@catlair+bilitools@0.5.220801/node_modules/@catlair/bilitools/dist/config/setConfig.js:130:43)
    at getConfig (/usr/local/pnpm-global/5/node_modules/.pnpm/@catlair+bilitools@0.5.220801/node_modules/@catlair/bilitools/dist/config/setConfig.js:144:22)
    at /usr/local/pnpm-global/5/node_modules/.pnpm/@catlair+bilitools@0.5.220801/node_modules/@catlair/bilitools/dist/index.ql.js:29:19

Node.js v17.8.0

## 执行结束... 2022-08-05 23:24:54 耗时 6 秒




然后我又尝试腾讯云函数的那个方法，跟的视频都走完了，包括ck填进，配置文件那了，不过都是包红的。报出下边的错误日志

START RequestId: f33b7c39-ae16-4fce-a7dc-7a27b0c8918f

[warn 23:12:03] SCF从6.1号其将不再拥有免费额度，暂时可以购买1元额度，请自行购买，谢谢！

Error: 获取配置失败！未找到配置文件！

    at checkConfig (/var/user/node_modules/@catlair/bilitools/dist/config/setConfig.js:149:11)

    at getConfig (/var/user/node_modules/@catlair/bilitools/dist/config/setConfig.js:144:10)

    at initialize (/var/user/node_modules/@catlair/bilitools/dist/config/globalVar.js:62:39)

    at Object.get (/var/user/node_modules/@catlair/bilitools/dist/config/globalVar.js:27:7)

    at Object.<anonymous> (/var/user/node_modules/@catlair/bilitools/dist/utils/log.js:77:34)

    at Module._compile (internal/modules/cjs/loader.js:1085:14)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

    at Module.load (internal/modules/cjs/loader.js:950:32)

ERROR RequestId: f33b7c39-ae16-4fce-a7dc-7a27b0c8918f Result: Error: 获取配置失败！未找到配置文件！     at checkConfig (/var/user/node_modules/@catlair/bilitools/dist/config/setConfig.js:149:11)     at getConfig (/var/user/node_modules/@catlair/bilitools/dist/config/setConfig.js:144:10)     at initialize (/var/user/node_modules/@catlair/bilitools/dist/config/globalVar.js:62:39)     at Object.get (/var/user/node_modules/@catlair/bilitools/dist/config/globalVar.js:27:7)     at Object.<anonymous> (/var/user/node_modules/@catlair/bilitools/dist/utils/log.js:77:34)     at Module._compile (internal/modules/cjs/loader.js:1085:14)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)     at Module.load (internal/modules/cjs/loader.js:950:32)

END RequestId: f33b7c39-ae16-4fce-a7dc-7a27b0c8918f

Report RequestId: f33b7c39-ae16-4fce-a7dc-7a27b0c8918f Duration: 22ms Memory: 128MB MemUsage: 16.82MB
```

### 有效的帮助

这个接口是这样的。。。

**Comment by Unicorni** [comment]
2022-08-05 23:55:39FC Invoke Start RequestId: ae514372-2c3a-4daa-82e0-a91890eef938
2022-08-05 23:55:39load code for handler:index.handler
2022-08-05 23:55:40[info 23:55:40] 阿里云 FC 测试ing
2022-08-05 23:55:40[verbose 23:55:40] 读取配置文件 /code/config.json5
2022-08-05 23:55:40[👻 23:55:40] 当前版本【v0.5.220801】
2022-08-05 23:55:40[👻 23:55:40] ----【登录】----
2022-08-05 23:55:40[👻 23:55:40] ----【消息推送】----
2022-08-05 23:55:40FC Invoke End RequestId: ae514372-2c3a-4daa-82e0-a91890eef938
2022-08-05 23:55:51FC Invoke Start RequestId: 279d8adb-8af2-4aa8-9e17-fed7547cb1bf
2022-08-05 23:55:51[👻 23:55:51] 阿里云 FC 测试ing
2022-08-05 23:55:51[👻 23:55:51] 当前版本【v0.5.220801】
2022-08-05 23:55:51[👻 23:55:51] ----【登录】----
2022-08-05 23:55:52[👻 23:55:52] ----【消息推送】----
2022-08-05 23:55:52FC Invoke End RequestId: 279d8adb-8af2-4aa8-9e17-fed7547cb1bf
2022-08-05 23:57:13FC Invoke Start RequestId: 43a16dcd-e53e-4215-bdf9-5784ed7258d1
2022-08-05 23:57:13[👻 23:57:13] 阿里云 FC 测试ing
2022-08-05 23:57:13[👻 23:57:13] 当前版本【v0.5.220801】
2022-08-05 23:57:13[👻 23:57:13] ----【登录】----
2022-08-05 23:57:13[👻 23:57:13] ----【消息推送】----
2022-08-05 23:57:13FC Invoke End RequestId: 43a16dcd-e53e-4215-bdf9-5784ed7258d1

**Comment by Unicorni** [comment]
首先感谢作者的教导，已经发现问题了，确实是配置文件里面出问题了，已经在本地和阿里云上部署运行成功，我首先在本地运行着，一直改那个.json5文件，才发现那个Cookie可能缺少一部分 _ uuid，然后再把那个阿里云的配置文档改了，居然能运行了，等起来我再研究一下直播如何抽奖设置，问个问题，win本地运行如何查看那个进程运行情况。

**Comment by KudouRan** [comment]
你说的日志吗，如果是用了那个cron工具，没法在控制台看，日志保存在配置文件同级目录的logs文件夹里，默认每个月一个文件，可以配置成每天。
如果是资源的进程，任务管理器。

**Comment by KudouRan** [comment]
天选时刻其实不建议使用，现在羊毛太少，黑号风险也高。
